Repository PotentialRadar/PR-Back, pull requests merged in 2025-08, with the labels that each got.

#41 fix: my page edit page
  src/main/java/com/potential_radar/PR/config/jwt/TokenAuthenticationFilter.java
  src/main/java/com/potential_radar/PR/config/jwt/TokenProvider.java
  src/main/java/com/potential_radar/PR/config/oauth/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/potential_radar/PR/user/controller/AuthController.java
  src/main/java/com/potential_radar/PR/user/domain/ExperienceRange.java
  src/main/java/com/potential_radar/PR/user/domain/User.java
  src/main/java/com/potential_radar/PR/user/domain/UserProfile.java
  src/main/java/com/potential_radar/PR/user/dto/UserProfileResponse.java
  src/main/java/com/potential_radar/PR/user/dto/UserProfileUpdateRequest.java
  src/main/java/com/potential_radar/PR/user/service/CustomOAuth2UserService.java
  src/main/java/com/potential_radar/PR/user/service/UserServiceImpl.java
Labels: 🐞 버그 (bug)

#48 Fix val,import
  src/main/java/com/potential_radar/PR/common/excetpion/GlobalExceptionHandler.java
  src/main/java/com/potential_radar/PR/config/WebSecurityConfig.java
  src/main/java/com/potential_radar/PR/like/domain/Like.java
  src/main/java/com/potential_radar/PR/like/repository/LikeRepository.java
  src/main/java/com/potential_radar/PR/like/service/LikeService.java
  src/main/java/com/potential_radar/PR/user/service/CustomOAuth2UserService.java
Labels: 🛠 리팩토링 (refactoring)

#50 Fix/project
  src/main/java/com/potential_radar/PR/common/domain/TechStack.java
  src/main/java/com/potential_radar/PR/common/repository/TechPartRepository.java
  src/main/java/com/potential_radar/PR/common/repository/TechStackRepository.java
  src/main/java/com/potential_radar/PR/like/domain/Like.java
  src/main/java/com/potential_radar/PR/like/repository/LikeRepository.java
  src/main/java/com/potential_radar/PR/like/service/LikeService.java
  src/main/java/com/potential_radar/PR/project/controller/CommentController.java
  src/main/java/com/potential_radar/PR/project/controller/ProjectApplicationController.java
  src/main/java/com/potential_radar/PR/project/controller/ProjectRecruitmentController.java
  src/main/java/com/potential_radar/PR/project/domain/ProjectTechPart.java
  src/main/java/com/potential_radar/PR/project/domain/ProjectTechStack.java
  src/main/java/com/potential_radar/PR/project/dto/ProjectApplicationResponseDTO.java
  src/main/java/com/potential_radar/PR/project/dto/ProjectRecruitmentRequest.java
  src/main/java/com/potential_radar/PR/project/dto/ProjectTechStackDTO.java
  src/main/java/com/potential_radar/PR/project/repository/ProjectApplicationRepository.java
  src/main/java/com/potential_radar/PR/project/repository/ProjectRecruitmentRepository.java
  src/main/java/com/potential_radar/PR/project/repository/ProjectTechPartRepository.java
  src/main/java/com/potential_radar/PR/project/service/CommentService.java
  src/main/java/com/potential_radar/PR/project/service/ProjectApplicationService.java
  src/main/java/com/potential_radar/PR/project/service/ProjectRecruitmentService.java
  src/main/java/com/potential_radar/PR/user/service/CustomOAuth2UserService.java
  src/main/java/com/potential_radar/PR/user/service/UserServiceImpl.java
Labels: ✨ 개선 (enhancement), 🛠 리팩토링 (refactoring)

#53 feat: AI 추천 API + 팀원 추천 + 기타 기능들
  ai-server/app/main.py
  ai-server/app/models.py
  ai-server/app/router/recommendation_router.py
  ai-server/app/routers/project_recommendation.py
  ai-server/app/schemas.py
  ai-server/app/schemas/project_recommendation.py
  ai-server/app/services/project_recommendation_service.py
  dummy_projects_data.sql
  src/main/java/com/potential_radar/PR/common/exception/AccessDeniedException.java
  src/main/java/com/potential_radar/PR/common/exception/DuplicateApplicationException.java
  src/main/java/com/potential_radar/PR/common/exception/ErrorResponse.java
  src/main/java/com/potential_radar/PR/common/exception/GlobalExceptionHandler.java
  src/main/java/com/potential_radar/PR/common/exception/InvalidTokenException.java
  src/main/java/com/potential_radar/PR/common/exception/NotFoundException.java
  src/main/java/com/potential_radar/PR/like/repository/LikeRepository.java
  src/main/java/com/potential_radar/PR/like/service/LikeService.java
  src/main/java/com/potential_radar/PR/project/controller/ProjectApplicationController.java
  src/main/java/com/potential_radar/PR/project/controller/ProjectRecruitmentController.java
  src/main/java/com/potential_radar/PR/project/service/CommentService.java
  src/main/java/com/potential_radar/PR/project/service/ProjectApplicationService.java
  src/main/java/com/potential_radar/PR/project/service/ProjectRecruitmentService.java
  src/main/java/com/potential_radar/PR/recommendation/controller/ProjectRecommendationController.java
  src/main/java/com/potential_radar/PR/recommendation/controller/RecommendationController.java
  src/main/java/com/potential_radar/PR/recommendation/dto/RecommendProjectRequest.java
  src/main/java/com/potential_radar/PR/recommendation/dto/RecommendedProject.java
  src/main/java/com/potential_radar/PR/recommendation/dto/UserTechStack.java
  src/main/java/com/potential_radar/PR/recommendation/service/ProjectRecommendationService.java
  src/main/java/com/potential_radar/PR/recommendation/service/TeamMemberRecommendationService.java
  src/main/java/com/potential_radar/PR/user/service/TokenService.java
  src/main/java/com/potential_radar/PR/user/service/UserServiceImpl.java
  team-member-recommendation-api-spec.md
Labels: ✨ 개선 (enhancement)

#56 fix: sql문 통합 및 TestDataInitializer 생성
  add_more_projects_correct.sql
  check_users_and_insert_projects.sql
  create_search_test_data.sql
  create_search_test_data.sql.bak
  data_insert.sql
  debug_project_search.http
  dummy_projects_data.sql
  insert_project_sample_data.sql
  simple_project_insert.sql
  src/main/java/com/potential_radar/PR/common/domain/BaseTimeEntity.java
  src/main/java/com/potential_radar/PR/config/TestDataInitializer.java
  src/main/java/com/potential_radar/PR/project/domain/ProjectRecruitment.java
  test-search-api.http
  test_project_search.http
  test_tech_tags.http
Labels: 🛠 리팩토링 (refactoring)

#57 fix: TestDataInitializer 수정(createdAt 데이터)
  src/main/java/com/potential_radar/PR/common/domain/BaseTimeEntity.java
  src/main/java/com/potential_radar/PR/config/TestDataInitializer.java
Labels: 🛠 리팩토링 (refactoring)

#58 feat: 리뷰 작성
  src/main/java/com/potential_radar/PR/common/exception/ErrorResponse.java
  src/main/java/com/potential_radar/PR/common/exception/GlobalExceptionHandler.java
  src/main/java/com/potential_radar/PR/project/controller/ProjectRecruitmentController.java
  src/main/java/com/potential_radar/PR/project/controller/TeamMemberReviewController.java
  src/main/java/com/potential_radar/PR/project/domain/ProjectRecruitment.java
  src/main/java/com/potential_radar/PR/project/domain/TeamMemberReview.java
  src/main/java/com/potential_radar/PR/project/dto/ProjectMemberResponseDTO.java
  src/main/java/com/potential_radar/PR/project/dto/ProjectRecruitmentRequest.java
  src/main/java/com/potential_radar/PR/project/dto/ProjectStatusUpdateRequest.java
  src/main/java/com/potential_radar/PR/project/dto/TeamMemberReviewRequestDto.java
  src/main/java/com/potential_radar/PR/project/repository/TeamMemberReviewRepository.java
  src/main/java/com/potential_radar/PR/project/service/ProjectRecruitmentService.java
  src/main/java/com/potential_radar/PR/project/service/TeamMemberReviewService.java
  src/main/java/com/potential_radar/PR/user/service/CustomOAuth2UserService.java
Labels: ✨ 개선 (enhancement)

#61 feat: 사용자 포트폴리오 조회/수정
  src/main/java/com/potential_radar/PR/config/WebSecurityConfig.java
  src/main/java/com/potential_radar/PR/techStack/domain/TechStackToDelete.java
  src/main/java/com/potential_radar/PR/techStack/repository/TechStackRepository.java
  src/main/java/com/potential_radar/PR/user/controller/AuthController.java
  src/main/java/com/potential_radar/PR/user/controller/PortfolioController.java
  src/main/java/com/potential_radar/PR/user/controller/UserController.java
  src/main/java/com/potential_radar/PR/user/domain/User.java
  src/main/java/com/potential_radar/PR/user/domain/UserEducation.java
  src/main/java/com/potential_radar/PR/user/domain/UserExperience.java
  src/main/java/com/potential_radar/PR/user/domain/UserTechStack.java
  src/main/java/com/potential_radar/PR/user/domain/UserTechStack1.java
  src/main/java/com/potential_radar/PR/user/dto/editInfo/UpdatedUserProfileResponse.java
  src/main/java/com/potential_radar/PR/user/dto/editInfo/UserProfileUpdateRequest.java
  src/main/java/com/potential_radar/PR/user/dto/editPortfolio/UpdatedUserPortfolioResponse.java
  src/main/java/com/potential_radar/PR/user/dto/editPortfolio/UserPortfolioUpdateRequest.java
  src/main/java/com/potential_radar/PR/user/dto/education/UserEducationRequest.java
  src/main/java/com/potential_radar/PR/user/dto/education/UserEducationResponse.java
  src/main/java/com/potential_radar/PR/user/dto/experience/UserExperienceRequest.java
  src/main/java/com/potential_radar/PR/user/dto/experience/UserExperienceResponse.java
  src/main/java/com/potential_radar/PR/user/dto/myPortfolio/OfficialPotfolioResponse.java
  src/main/java/com/potential_radar/PR/user/dto/techStack/UserTechStackRequest.java
  src/main/java/com/potential_radar/PR/user/dto/techStack/UserTechStackResponse.java
  src/main/java/com/potential_radar/PR/user/repository/UserEducationRepository.java
  src/main/java/com/potential_radar/PR/user/repository/UserExperienceRepository.java
  src/main/java/com/potential_radar/PR/user/repository/UserTechStackRepository.java
  src/main/java/com/potential_radar/PR/user/service/CustomOAuth2UserService.java
  src/main/java/com/potential_radar/PR/user/service/EducationService.java
  src/main/java/com/potential_radar/PR/user/service/ExperienceService.java
  src/main/java/com/potential_radar/PR/user/service/PortfolioService.java
  src/main/java/com/potential_radar/PR/user/service/TechStackService.java
  src/main/java/com/potential_radar/PR/user/service/UserService.java
  src/main/java/com/potential_radar/PR/user/service/impl/EducationServiceImpl.java
  src/main/java/com/potential_radar/PR/user/service/impl/ExperienceServiceImpl.java
  src/main/java/com/potential_radar/PR/user/service/impl/PortfolioServiceImpl.java
  src/main/java/com/potential_radar/PR/user/service/impl/TechStackServiceImpl.java
  src/main/java/com/potential_radar/PR/user/service/impl/UserServiceImpl.java
Labels: ✨ 개선 (enhancement)

#62 fix:mergeBug
  src/main/java/com/potential_radar/PR/project/service/ProjectRecruitmentService.java
  src/main/java/com/potential_radar/PR/search/service/DataSyncService.java
  src/main/java/com/potential_radar/PR/tech/domain/TechStack.java
  src/main/java/com/potential_radar/PR/tech/repository/TechStackRepository.java
  src/main/java/com/potential_radar/PR/techStack/repository/TechStackRepository.java
  src/main/java/com/potential_radar/PR/user/domain/User.java
  src/main/java/com/potential_radar/PR/user/domain/UserTechStack.java
  src/main/java/com/potential_radar/PR/user/dto/techStack/UserTechStackResponse.java
  src/main/java/com/potential_radar/PR/user/repository/UserTechStackRepository.java
  src/main/java/com/potential_radar/PR/user/service/impl/PortfolioServiceImpl.java
  src/main/java/com/potential_radar/PR/user/service/impl/TechStackServiceImpl.java
Labels: 🐞 버그 (bug)

#63 feat: notification
  src/main/java/com/potential_radar/PR/config/TestDataInitializer.java
  src/main/java/com/potential_radar/PR/notification/controller/NotificationController.java
  src/main/java/com/potential_radar/PR/notification/domain/Notification.java
  src/main/java/com/potential_radar/PR/notification/domain/NotificationContent.java
  src/main/java/com/potential_radar/PR/notification/domain/NotificationType.java
  src/main/java/com/potential_radar/PR/notification/dto/NotificationDto.java
  src/main/java/com/potential_radar/PR/notification/dto/NotificationPageResDto.java
  src/main/java/com/potential_radar/PR/notification/repository/EmitterRepository.java
  src/main/java/com/potential_radar/PR/notification/repository/EmitterRepositoryImpl.java
  src/main/java/com/potential_radar/PR/notification/repository/NotificationRepository.java
  src/main/java/com/potential_radar/PR/notification/service/NotificationService.java
  src/main/java/com/potential_radar/PR/project/controller/CommentController.java
  src/main/java/com/potential_radar/PR/project/service/CommentService.java
  src/main/java/com/potential_radar/PR/project/service/ProjectApplicationService.java
Labels: ✨ 개선 (enhancement)

#64 feat: 프로젝트 좋아요
  src/main/java/com/potential_radar/PR/config/TestDataInitializer.java
  src/main/java/com/potential_radar/PR/like/controller/LikeController.java
  src/main/java/com/potential_radar/PR/like/domain/Like.java
  src/main/java/com/potential_radar/PR/like/dto/LikeStatusResponseDto.java
  src/main/java/com/potential_radar/PR/like/service/LikeService.java
  src/main/java/com/potential_radar/PR/project/controller/ProjectRecruitmentController.java
  src/main/java/com/potential_radar/PR/project/dto/ProjectRecruitmentResponse.java
  src/main/java/com/potential_radar/PR/project/service/ProjectApplicationService.java
  src/main/java/com/potential_radar/PR/project/service/ProjectRecruitmentService.java
  src/main/java/com/potential_radar/PR/user/controller/UserController.java
Labels: ✨ 개선 (enhancement)

#65 feat: 팀원 초대 기능 , TestDataInitializer 수정
  ai-server/app/main.py
  ai-server/app/ml/generate_training_data.py
  ai-server/app/models.py
  ai-server/app/router/recommendation_router.py
  ai-server/app/router/team_recommendation_router.py
  ai-server/app/routers/project_recommendation.py
  ai-server/app/schemas.py
  ai-server/app/schemas/project_recommendation.py
  ai-server/app/services/project_recommendation_service.py
  ai-server/app/utils/feature_engineering.py
  ai-server/app/utils/like_analyzer.py
  ai-server/app/utils/preprocess.py
  data_insert.sql
  src/main/java/com/potential_radar/PR/common/exception/GlobalExceptionHandler.java
  src/main/java/com/potential_radar/PR/common/exception/InvitationException.java
  src/main/java/com/potential_radar/PR/common/exception/RecommendationServiceException.java
  src/main/java/com/potential_radar/PR/config/TestDataInitializer.java
  src/main/java/com/potential_radar/PR/invitation/controller/TeamInvitationController.java
  src/main/java/com/potential_radar/PR/invitation/domain/InvitationStatus.java
  src/main/java/com/potential_radar/PR/invitation/domain/TeamInvitation.java
  src/main/java/com/potential_radar/PR/invitation/dto/TeamInvitationDto.java
  src/main/java/com/potential_radar/PR/invitation/repository/TeamInvitationRepository.java
  src/main/java/com/potential_radar/PR/invitation/service/TeamInvitationService.java
  src/main/java/com/potential_radar/PR/recommendation/controller/ProjectRecommendationController.java
  src/main/java/com/potential_radar/PR/recommendation/controller/RecommendationController.java
  src/main/java/com/potential_radar/PR/recommendation/domain/RecommendationHistory.java
  src/main/java/com/potential_radar/PR/recommendation/dto/LikedProject.java
  src/main/java/com/potential_radar/PR/recommendation/dto/RecommendProjectRequest.java
  src/main/java/com/potential_radar/PR/recommendation/dto/RecommendRequest.java
  src/main/java/com/potential_radar/PR/recommendation/dto/RecommendedMember.java
  src/main/java/com/potential_radar/PR/recommendation/dto/RecommendedProject.java
  src/main/java/com/potential_radar/PR/recommendation/dto/RecommendedProjectResponse.java
  src/main/java/com/potential_radar/PR/recommendation/dto/UserTechStack.java
  src/main/java/com/potential_radar/PR/recommendation/service/ProjectRecommendationService.java
  src/main/java/com/potential_radar/PR/recommendation/service/RecommendationService.java
  src/main/java/com/potential_radar/PR/recommendation/service/TeamMemberRecommendationService.java
Labels: ✨ 개선 (enhancement), 🛠 리팩토링 (refactoring)

#68 Feat/search project
  src/main/java/com/potential_radar/PR/config/WebMvcConfig.java
  src/main/java/com/potential_radar/PR/search/config/CacheConfig.java
  src/main/java/com/potential_radar/PR/search/controller/SearchController.java
  src/main/java/com/potential_radar/PR/search/dto/TechTagsRes.java
  src/main/java/com/potential_radar/PR/search/service/DataSyncService.java
  src/main/java/com/potential_radar/PR/search/service/SearchService.java
  src/main/java/com/potential_radar/PR/tech/service/TechPartService.java
  src/main/java/com/potential_radar/PR/techStack/domain/TechStackToDelete.java
Labels: ✨ 개선 (enhancement)

#69 feat: 프로젝트 최신순, 인기순 정렬
  src/main/java/com/potential_radar/PR/like/repository/LikeRepository.java
  src/main/java/com/potential_radar/PR/like/service/LikeService.java
  src/main/java/com/potential_radar/PR/project/controller/ProjectApplicationController.java
  src/main/java/com/potential_radar/PR/project/controller/ProjectRecruitmentController.java
  src/main/java/com/potential_radar/PR/project/dto/ProjectApplyRequest.java
  src/main/java/com/potential_radar/PR/project/dto/ProjectRecruitmentResponse.java
  src/main/java/com/potential_radar/PR/project/repository/ProjectRecruitmentRepository.java
  src/main/java/com/potential_radar/PR/project/service/ProjectApplicationService.java
  src/main/java/com/potential_radar/PR/project/service/ProjectRecruitmentService.java
Labels: 🐞 버그 (bug), ✨ 개선 (enhancement)

#70 Fix/mypage/portfolio
  gradlew
  src/main/java/com/potential_radar/PR/common/exception/GlobalExceptionHandler.java
  src/main/java/com/potential_radar/PR/config/TestDataInitializer.java
  src/main/java/com/potential_radar/PR/project/repository/ProjectTechStackRepository.java
  src/main/java/com/potential_radar/PR/project/repository/TeamMemberReviewRepository.java
  src/main/java/com/potential_radar/PR/search/controller/SearchController.java
  src/main/java/com/potential_radar/PR/tech/controller/TechPartController.java
  src/main/java/com/potential_radar/PR/tech/controller/TechStackController.java
  src/main/java/com/potential_radar/PR/tech/service/TechPartService.java
  src/main/java/com/potential_radar/PR/user/controller/PortfolioController.java
  src/main/java/com/potential_radar/PR/user/controller/PortfolioListController.java
  src/main/java/com/potential_radar/PR/user/controller/PublicPortfolioController.java
  src/main/java/com/potential_radar/PR/user/controller/UserController.java
  src/main/java/com/potential_radar/PR/user/controller/UserReviewController.java
  src/main/java/com/potential_radar/PR/user/domain/PortfolioProject.java
  src/main/java/com/potential_radar/PR/user/dto/editPortfolio/UpdatedUserPortfolioResponse.java
  src/main/java/com/potential_radar/PR/user/dto/editPortfolio/UserPortfolioUpdateRequest.java
  src/main/java/com/potential_radar/PR/user/dto/myPortfolio/OfficialPotfolioResponse.java
  src/main/java/com/potential_radar/PR/user/dto/portfolios/PortfolioListResponse.java
  src/main/java/com/potential_radar/PR/user/dto/portfolios/PortfolioSearchRequest.java
  src/main/java/com/potential_radar/PR/user/dto/portfolios/PortfolioSummaryResponse.java
  src/main/java/com/potential_radar/PR/user/dto/project/PortfolioProjectSelectionRequest.java
  src/main/java/com/potential_radar/PR/user/dto/project/UserAvailableProjectsResponse.java
  src/main/java/com/potential_radar/PR/user/dto/project/UserProjectResponse.java
  src/main/java/com/potential_radar/PR/user/dto/review/UserReceivedReviewResponse.java
  src/main/java/com/potential_radar/PR/user/repository/PortfolioProjectRepository.java
  src/main/java/com/potential_radar/PR/user/repository/UserProfileRepository.java
  src/main/java/com/potential_radar/PR/user/service/CustomOAuth2UserService.java
  src/main/java/com/potential_radar/PR/user/service/PortfolioListService.java
  src/main/java/com/potential_radar/PR/user/service/PortfolioService.java
  src/main/java/com/potential_radar/PR/user/service/PublicPortfolioService.java
  src/main/java/com/potential_radar/PR/user/service/UserReviewService.java
  src/main/java/com/potential_radar/PR/user/service/impl/PortfolioListServiceImpl.java
  src/main/java/com/potential_radar/PR/user/service/impl/PortfolioServiceImpl.java
  src/main/java/com/potential_radar/PR/user/service/impl/PublicPortfolioServiceImpl.java
  src/main/java/com/potential_radar/PR/user/service/impl/UserServiceImpl.java
Labels: 🐞 버그 (bug)

#73 fix: 충돌해결
  src/main/java/com/potential_radar/PR/recommendation/service/RecommendationService.java
  src/main/java/com/potential_radar/PR/search/controller/SearchController.java
  src/main/java/com/potential_radar/PR/tech/service/TechPartService.java
Labels: 🛠 리팩토링 (refactoring)

#74 Fix/project(create)
  src/main/java/com/potential_radar/PR/common/S3/S3Uploader.java
  src/main/java/com/potential_radar/PR/project/controller/ProjectRecruitmentController.java
  src/main/java/com/potential_radar/PR/project/domain/ProjectRecruitment.java
  src/main/java/com/potential_radar/PR/project/dto/ProjectRecruitmentRequest.java
  src/main/java/com/potential_radar/PR/project/dto/ProjectRecruitmentResponse.java
  src/main/java/com/potential_radar/PR/project/service/ProjectRecruitmentService.java
Labels: 🐞 버그 (bug)

#76 fix: 알림 연결 및 기준 정보성 데이터 캐싱(TechPart, TechStack, ExperienceRange)
  src/main/java/com/potential_radar/PR/config/TestDataInitializer.java
  src/main/java/com/potential_radar/PR/like/service/LikeService.java
  src/main/java/com/potential_radar/PR/notification/domain/NotificationType.java
  src/main/java/com/potential_radar/PR/notification/service/DeadlineNotificationService.java
  src/main/java/com/potential_radar/PR/notification/service/ProjectEndDateNotificationService.java
  src/main/java/com/potential_radar/PR/project/controller/ProjectRecruitmentController.java
  src/main/java/com/potential_radar/PR/project/domain/ProjectRecruitment.java
  src/main/java/com/potential_radar/PR/project/dto/ProjectRecruitmentRequest.java
  src/main/java/com/potential_radar/PR/project/dto/ProjectRecruitmentResponse.java
  src/main/java/com/potential_radar/PR/project/repository/ProjectRecruitmentRepository.java
  src/main/java/com/potential_radar/PR/project/service/ProjectApplicationService.java
  src/main/java/com/potential_radar/PR/project/service/ProjectRecruitmentService.java
  src/main/java/com/potential_radar/PR/search/service/DataSyncService.java
  src/main/java/com/potential_radar/PR/search/service/SearchService.java
  src/main/java/com/potential_radar/PR/user/repository/UserRepository.java
Labels: 🛠 리팩토링 (refactoring)

#78 Rollback/search
  src/main/java/com/potential_radar/PR/project/repository/ProjectRecruitmentRepository.java
  src/main/java/com/potential_radar/PR/search/controller/DataSyncController.java
  src/main/java/com/potential_radar/PR/search/controller/SearchController.java
  src/main/java/com/potential_radar/PR/search/document/UserSearchDocument.java
  src/main/java/com/potential_radar/PR/search/repository/SyncStatusRepository.java
  src/main/java/com/potential_radar/PR/search/service/DataSyncService.java
  src/main/java/com/potential_radar/PR/search/service/IncrementalSyncScheduler.java
  src/main/java/com/potential_radar/PR/search/service/SearchService.java
  src/main/java/com/potential_radar/PR/user/repository/UserRepository.java
  src/main/resources/elasticsearch/user-index-mapping.json
Labels: ✨ 개선 (enhancement)

#79 fix/S3버그수정, 디테일추가
  src/main/java/com/potential_radar/PR/project/domain/ProjectRecruitment.java
  src/main/java/com/potential_radar/PR/project/dto/ProjectAttachmentDto.java
  src/main/java/com/potential_radar/PR/project/dto/ProjectRecruitmentRequest.java
  src/main/java/com/potential_radar/PR/project/dto/ProjectRecruitmentResponse.java
  src/main/java/com/potential_radar/PR/project/service/ProjectApplicationService.java
  src/main/java/com/potential_radar/PR/project/service/ProjectRecruitmentService.java
Labels: 🐞 버그 (bug), 🎨 디자인 (design)

#82 Fix tokenstorage
  src/main/java/com/potential_radar/PR/config/WebSecurityConfig.java
  src/main/java/com/potential_radar/PR/config/jwt/JwtProperties.java
  src/main/java/com/potential_radar/PR/config/jwt/TokenAuthenticationFilter.java
  src/main/java/com/potential_radar/PR/config/jwt/TokenProvider.java
  src/main/java/com/potential_radar/PR/config/oauth/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/potential_radar/PR/user/controller/AuthController.java
  src/main/java/com/potential_radar/PR/user/controller/PortfolioListController.java
  src/main/java/com/potential_radar/PR/user/controller/PublicPortfolioController.java
  src/main/java/com/potential_radar/PR/user/controller/TokenApiController.java
  src/main/java/com/potential_radar/PR/user/controller/UserController.java
  src/main/java/com/potential_radar/PR/user/domain/RefreshToken.java
  src/main/java/com/potential_radar/PR/user/domain/UserEducation.java
  src/main/java/com/potential_radar/PR/user/domain/UserExperience.java
  src/main/java/com/potential_radar/PR/user/dto/portfolios/PortfolioListResponse.java
  src/main/java/com/potential_radar/PR/user/dto/portfolios/PortfolioSearchRequest.java
  src/main/java/com/potential_radar/PR/user/dto/portfolios/PortfolioSummaryResponse.java
  src/main/java/com/potential_radar/PR/user/service/PortfolioListService.java
  src/main/java/com/potential_radar/PR/user/service/impl/PortfolioListServiceImpl.java
  src/main/java/com/potential_radar/PR/user/service/impl/PortfolioServiceImpl.java
Labels: 🐞 버그 (bug), ✨ 개선 (enhancement), 🛠 리팩토링 (refactoring)
