Repository PotentialRadar/PR-Back, pull requests merged in 2025-09, with the labels that each got.

#83 feat: 포트폴리오 리스트 관련 api 수정
  src/main/java/com/potential_radar/PR/config/TestDataInitializer.java
  src/main/java/com/potential_radar/PR/config/WebSecurityConfig.java
  src/main/java/com/potential_radar/PR/user/controller/PortfolioListController.java
  src/main/java/com/potential_radar/PR/user/dto/portfolios/PortfolioListResponse.java
  src/main/java/com/potential_radar/PR/user/dto/portfolios/PortfolioSearchRequest.java
  src/main/java/com/potential_radar/PR/user/dto/portfolios/PortfolioSummaryResponse.java
  src/main/java/com/potential_radar/PR/user/service/PortfolioListService.java
  src/main/java/com/potential_radar/PR/user/service/impl/PortfolioListServiceImpl.java
Labels: ✨ 개선 (enhancement)

#87 refactor
  src/main/java/com/potential_radar/PR/config/TestDataInitializer.java
  src/main/java/com/potential_radar/PR/user/service/impl/PortfolioServiceImpl.java
Labels: 🐞 버그 (bug)

#88 필터링 수정
  src/main/java/com/potential_radar/PR/config/TestDataInitializer.java
  src/main/java/com/potential_radar/PR/project/repository/ProjectTechStackRepository.java
  src/main/java/com/potential_radar/PR/search/controller/PopularSearchController.java
  src/main/java/com/potential_radar/PR/search/controller/SearchController.java
  src/main/java/com/potential_radar/PR/search/event/CacheInvalidationListener.java
  src/main/java/com/potential_radar/PR/search/service/DataSyncService.java
  src/main/java/com/potential_radar/PR/search/service/PopularSearchService.java
  src/main/java/com/potential_radar/PR/search/service/SearchCacheService.java
  src/main/java/com/potential_radar/PR/search/service/SearchService.java
  src/main/java/com/potential_radar/PR/user/repository/UserTechStackRepository.java
Labels: 🐞 버그 (bug), ✨ 개선 (enhancement)

#90 Update UserReviewService.java
  src/main/java/com/potential_radar/PR/user/service/UserReviewService.java
Labels: 🐞 버그 (bug), ✨ 개선 (enhancement)

#93 Refactor data init
  data_insert.sql
  src/main/java/com/potential_radar/PR/config/TestDataInitializer.java
  src/main/resources/data.sql
  src/main/resources/schema.sql
Labels: ✨ 개선 (enhancement)

#99 엘라스틱 정렬 수정
  src/main/java/com/potential_radar/PR/search/service/SearchCacheService.java
  src/main/resources/data.sql
Labels: 🐞 버그 (bug)

#103 Update TechPartService.java
  src/main/java/com/potential_radar/PR/tech/service/TechPartService.java
Labels: 🐞 버그 (bug)

#105 fix caching
  src/main/java/com/potential_radar/PR/search/config/SmartCacheConfig.java
  src/main/java/com/potential_radar/PR/search/event/CacheInvalidationListener.java
  src/main/java/com/potential_radar/PR/search/service/PopularSearchService.java
  src/main/java/com/potential_radar/PR/search/service/SearchService.java
  src/main/java/com/potential_radar/PR/search/service/SmartCacheService.java
  src/main/resources/data.sql
  src/test/java/com/potential_radar/PR/search/service/CacheDebugTest.java
  src/test/java/com/potential_radar/PR/search/service/CacheMockTest.java
  src/test/java/com/potential_radar/PR/search/service/CacheValidationTest.java
  src/test/java/com/potential_radar/PR/search/service/FinalCacheValidationTest.java
  src/test/java/com/potential_radar/PR/search/service/PopularSearchServiceTest.java
  src/test/java/com/potential_radar/PR/search/service/SmartCacheServiceIntegrationTest.java
  src/test/java/com/potential_radar/PR/search/service/SmartCacheServiceTest.java
Labels: 🐞 버그 (bug)

#106 feat:connection pool
  ai-server/app/database.py
  build.gradle
  src/main/java/com/potential_radar/PR/config/TestDataInitializer.java
  src/main/java/com/potential_radar/PR/tech/service/TechPartService.java
Labels: ✨ 개선 (enhancement)
